package com.gl.ceir;

public interface ProcessName {
	
	String REGISTERED_DEVICE_TAX_NOT_PAID_REMINDER = "REGISTERED_DEVICE_TAX_NOT_PAID_REMINDER";
	String VISA_EXPIRE = "VISA_EXPIRE";
	String CONSIGNMENT_REVENUE = "CONSIGNMENT_REVENUE";
	String CLOSE_GRIEVANCE = "CLOSE_GRIEVANCE";
	String BLOCK_END_USER_DEVICE = "BLOCK_END_USER_DEVICE";
	String REMOVE_IN_COMPLETE_USER = "REMOVE_IN_COMPLETE_USER";
	String FIND_USER_REG = "FIND_USER_REG";
	String REMOVE_FROM_BLACKLIST = "REMOVE_FROM_BLACKLIST";

}

