package com.gl.ceir.config.model.constants;

public enum TransactionState {
	INIT, SEND_TO_COMM, WAITING_FOR_USER_ACTION, FOR_NOTIFICATION, SEND_TO_BLOCK, SEND_TO_ALOW, FINISH, WAIT_FOR_DOCUMENT_APPROVAL, DOCUMENT_REJECTED, DOCUMENT_APPROVED;
}
